Suppress context when requests.exceptions.JSONDecodeError is raised.
When a JSON response cannot be parsed, requests catch json.JSONDecodeError
(or simplejson.JSONDecodeError) and raise requests.exceptions.JSONDecodeError instead.
Because this happens in an except block, unhandled exceptions were printed in a chain:

```
Traceback (most recent call last):
...
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
...
requests.exceptions.JSONDecodeError: [Errno Expecting value] ...
```

This seems unnecessary and it increases cognitive overhead whean examining errors.

As requests.exceptions.JSONDecodeError inherits json.JSONDecodeError and
we copy all atrributes from the later to the former,
`raise ... from None` seems more approriate than `raise ... from e`.